version: 2

models:

  - name: campaigns
    materialized: table
    columns:

      - name: account_name
        type: string

      - name: account_id
        type: string
        tests:
          - not_null
      
      - name: campaign_name
        type: string
      
      - name: campaign_id
        type: string
      
      - name: status
        type: string
      
      - name: objective
        type: string
        tests:
          - not_null
      
      - name: start_time
        type: timestamp
      
      - name: daily_budget
        type: numeric
      
      - name: effective_status
        type: string


  - name: ad_sets
    materialized: table
    columns:

      - name: account_name
        type: string

      - name: account_id
        type: string
        tests:
          - not_null
      
      - name: campaign_name
        type: string
      
      - name: campaign_id
        type: string
        tests:
          - not_null
      
      - name: ad_set_name
        type: string

      - name: ad_set_id
        type: string
        tests:
          - not_null
      
      - name: start_time
        type: timestamp

      - name: effective_status
        type: string


  - name: ads
    materialized: table
    columns:

      - name: account_name
        type: string

      - name: account_id
        type: string
        tests:
          - not_null
      
      - name: campaign_name
        type: string
      
      - name: campaign_id
        type: string
        tests:
          - not_null
      
      - name: ad_set_name
        type: string

      - name: ad_set_id
        type: string
        tests:
          - not_null
      
      - name: creative_id
        type: string
      
      - name: creative_image
        type: string